# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Tyk


class _Component(_Tyk):
    _type = "component"
    _icon_dir = "resources/tyk/component"


class Dashboard(_Component):
    _icon = "dashboard.png"


class Gateway(_Component):
    _icon = "gateway.png"


class MDCB(_Component):
    _icon = "mdcb.png"


class Pump(_Component):
    _icon = "pump.png"


# Aliases
