# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Tyk


class _Component(_Tyk):
    _type = "component"
    _icon_dir = "resources/tyk/component"


class Gateway(_Component):
    _icon = "gateway.png"


# Aliases
